### ISSUE TITLE
Migrating MigraDoc to .NET Standard 2.0 based on this fork of PDFSharp?

### ISSUE THREAD

**Issue by tudorserbanconnatix** [Didstopia/PDFSharp#15]
I've not studied this in-depth but it seems to me that the only thing preventing MigraDoc from targeting .NET Standard 2.0 is the lack of a PDFSharp port due to it still referencing System.Drawing. Would a fork of MigraDoc referencing this PDFSharp fork and targeting .NET Standard 2.0 be feasible (with only a subset of the features ofc)?

**Comment by Dids** [comment]
Definitely. See the discussion in #16 on where this fork is (hopefully) heading.

**Comment by ronnyek** [comment]
I've actually just finished getting this integrated and building, just need to write up some tests... looks like everything should be there minus the desktop preview, native windows printing, and charting support. Seems like charting could be added back and probably in a *LOT* more robust fashion

**Comment by tudorserbanconnatix** [comment]
Here's what I've been working on: https://github.com/tudorserbanconnatix/MigraDoc It's a very basic change to MigraDoc that involved retargeting all projects to .NET Standard and referencing this fork of PDFSharp instead of the original, plus a couple of fixes.

**Comment by ronnyek** [comment]
Shoot... so basically what I did was suck in the Migradoc library as whats there isnt too big. Didstopia fork for me currently just has a Migradoc folder within. Seems to me like having raw pdf functionality is valuable, but often times (at least for me) I've always just referenced migradoc anyway. 

Ultimately I think the migradoc could stand to have quite a bit of refactoring to make it more pleasant to deal with, but first things first. 

Maybe @Dids can chime in with how to move forward with migradoc. I just tested the migradoc functionality, and it works, but was going to just roll up a large example document in migradoc and figure out a way to legitimately test it.

**Comment by Dids** [comment]
If I understood the question correctly (if there was one, hehe), I'd rather keep them as two completely separate projects, instead of bundling them together.

**Comment by Dids** [comment]
Any news on this?

**Comment by Dids** [comment]
I guess #16 is also related to this?

**Comment by tudorserbanconnatix** [comment]
@Dids : Not sure if you are addressing me or @ronnyek. For my own needs what I have here is good enough: [https://github.com/tudorserbanconnatix/MigraDoc](https://github.com/tudorserbanconnatix/MigraDoc)

**Comment by Dids** [comment]
Thanks! In that case I'll close this one for now.
