### ISSUE TITLE
Broken Test

### ISSUE THREAD

**Issue by steveoh** [Didstopia/PDFSharp#24]
I installed this package from nuget and copied the data necessary to run this [acroforms test](https://github.com/Didstopia/PDFSharp/blob/c0e79a42b1025f8809fed4f40b4f1dd999c90996/Didstopia.PDFSharp.Tests/PDFSharpTests.cs#L137-L180) and it failed with a nullreferenceexception when trying to find the field from the form.Fields collection. 

Fyi, it works in the empira rc-2 release. Thought you might want to know.

**Comment by Dids** [comment]
Can you try it again with the latest version from NuGet (v1.0.0-beta7)?

That should now include the latest fixes. Note that it might take a few minutes for NuGet to show the new package version.

**Comment by Dids** [comment]
This seems to be fixed, so closing the issue.
