### ISSUE TITLE
Source code 1.50 beta 3b - Missing text

### ISSUE THREAD

**Issue by groege** [Didstopia/PDFSharp#4]
Hi,
I realized you used the latest PDFSharp source, and merged code from https://github.com/roceh/PdfSharp.Xamarin and https://github.com/groege/PdfSharpCore
which obviously is fine (though i think it would be nice to mention roceh in your project, since he did the bulk of the code changes needed for portability...), but in my repo "https://github.com/groege/PdfSharpCore" if found out, that when I try to print to a Kyocera printer from an Android phone, depending on how I try to print it, text might be missing or it won't print at all (the preview was fine though - it seems to be an issue with the print script...).
The same issue happened in older versions of the original PDFSharp as well.
Do you think this is fixed with your project? Do you have any time to try it out or send me a Pdf, created by your project, that I can try to print?

**Comment by Dids** [comment]
Hey @groege,

Thanks for reminding about the licenses! I'm pushing the license attribution fixes in a few minutes, still very much a work in progress as targeting .NET Standard 2.0 was more painful than I initially thought. :)

Could you create a separate issue for the printing part, so I can see if I can test it and get it working? Also is it only on Android & Kyocera, or just printing in general?

There seems to be quite a lot that's broken, including encryption support, but I'm fairly sure those are fixable on way or another. Right now I'm concentrating on getting the library working in both .NET Standard and Core projects, as well as writing unit tests for all core features of PDFSharp.

**Comment by groege** [comment]
No problem ;)
I actually found a Solution for the printing part - it's not a bug of PdfSharp!
The the problem lies with printing drivers.
I implemented a printing function for UWP (works wonderfully on Windows Phone 10) which works on Kyocera.
For Android, if the printer driver doesn't work properly with your Pdf,  you can just install "Let's Print  Droid" and "Let's Print Pdf", which can be used in place of the Vendors drivers (those two apps actually try to find the proper protocol to send the data to the printer, in my case i think it converts the pdf to postscript which then can be printed properly instead of sending the pdf which isnt' fully supported on the printer. If you want a more specific description on how to make it work, you can always ask ;) ) 
So now I can print on Windows Phone as well as Android without issues - without changing the code.

**Comment by Dids** [comment]
Ahh, thanks, that'll come in handy later! :)
